#!/bin/bash
set -euo pipefail

: ${SCREEN_GEOMETRY:=$(fbset --info | perl -anle 'print "$F[1]x$F[2]" and last if /geometry/')}
: ${BACKGROUND_COLOR:=black}

main() {
    local fb="${1:-/dev/fb0}"

    report "🖼 Generating bitmap"
    convert \
        \( -size "$SCREEN_GEOMETRY" canvas:"$BACKGROUND_COLOR" \) \
        \( - -scale "$SCREEN_GEOMETRY>" -auto-orient \) \
        -gravity center \
        -compose copy \
        -composite \
        -alpha opaque \
        -depth 8 \
        bgra:"$fb"
    report "🖼 done in ${SECONDS}s"
}

report() {
    echo "$@" >&2
}

main "$@"
