#!/bin/bash
set -euo pipefail

: ${BACKGROUND_COLOR:=black}

main() {
    local fb="${1:-/dev/fb0}"
    local geometry="$(fbset -fb "$fb" --info | perl -anle 'print "$F[1]x$F[2]" and last if /geometry/')"

    report "🖼 Generating bitmap"
    convert \
        \( -size "$geometry" canvas:"$BACKGROUND_COLOR" \) \
        \( - -scale "$geometry>" -auto-orient \) \
        -gravity center \
        -compose copy \
        -composite \
        -alpha opaque \
        -depth 8 \
        bgra:"$fb"
    report "🖼 done in ${SECONDS}s"
}

report() {
    if [[ -t 0 ]]; then
        echo "$@" >&2
    fi
}

main "$@"
